java_library(
    name = "position_test",
    srcs = ["PositionTest.java"],
    deps =[
        "//:java_test_lib_deps",
        "//src/main/java/bzlexample/maps:maps"
    ],
    # 仅对 WORKSPACE 下的 :alltests 可见
    visibility = ["//:__pkg__"],
)
